version: '3.4'
services:
  php:
    container_name: php
    user: "$USER_ID:$GROUP_ID"
    build:
      context: ./docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      COMPOSER_HOME: /tmp/composer
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
